### ISSUE TITLE
ImportError: cannot import name 'SecureHeaders' from 'secure'

### ISSUE THREAD

**Issue by yupthatguy** [smicallef/spiderfoot#1166]
**Please provide a description of the issue and any relevant error messages.

I follow these instructions to install spiderfoot on Debian 10 
https://www.howtoforge.com/how-to-install-spiderfoot-on-ubuntu-20-04/

However, whenever I run:

`python3 sf.py --help`

I get:

```
# python3 sf.py --help
Traceback (most recent call last):
  File "sf.py", line 32, in <module>
    from sfwebui import SpiderFootWebUi
  File "/root/python-environments/spiderfoot-3.3/sfwebui.py", line 27, in <module>
    from secure import SecureHeaders
ImportError: cannot import name 'SecureHeaders' from 'secure' (/root/python-environments/spiderfoot-env/lib/python3.7/site-packages/secure/__init__.py)
```

**What version of Python are you using?

I have python 2.7 and 3.7 installed.  I am using python 3.7 in a virtual environment  to install. 

My Steps:
```
#pip3 install --upgrade pip
#pip3 install wheel
#wget https://github.com/smicallef/spiderfoot/archive/v3.3.tar.gz
#tar -xvzf v3.3.tar.gz
#cd spiderfoot-3.3
#pip3 install -r requirements.txt
#python3 sf.py --help
```

ERROR (see above)

I tried with `secure-0.2.1` in the requirements.txt I tried again after editing requirements.txt to use `secure-0.3.0`, but same error  

**What version of SpiderFoot are you using (stable release or Git `master` branch)?

https://github.com/smicallef/spiderfoot/archive/v3.3.tar.gz

**Comment by bcoles** [comment]
> I tried with secure-0.2.1 in the requirements.txt I tried again after editing requirements.txt to use secure-0.3.0, but same error

SpiderFoot will only work with secure version 0.2.1. You may have to remove newer version of secure (ie, 3.x).

Your requirements file should look like this:

https://github.com/smicallef/spiderfoot/blob/master/requirements.txt

**Comment by yupthatguy** [comment]
Hey hey, thanks for the help.  Turns out that the requirements.txt that I downloaded with:
`wget https://github.com/smicallef/spiderfoot/archive/v3.3.tar.gz` 
is simply incorrect. 

Just before before I ran:

`pip3 install -r requirements.txt`

I first made a backup of the requirements.txt -> requirements.txt.bak
Then, I made a new requirements.txt file and copy & pasted your content from:
`https://github.com/smicallef/spiderfoot/blob/master/requirements.txt`
Sure, enough I was able to complete the install without any further problems.

FYI I ran a quick diff check of requirements.txt (yours) and requirements.txt.bak (the original downloaded in the tar.gz), it showed several lines are different and were causing my headache:
```
diff requirements.txt requirements.txt.bak
8c8
< lxml>=4.6.3
---
> lxml>=4.6.2
19c19
< secure>=0.2.1,<0.3.0
---
> secure>=0.2.1
24c24
< cryptography>=3.3.2
---
> cryptography>=3.3.0
```

The installation went smoothly, so we can close this issued as solved. A new issue arose when trying to run spiderfoot on my prod server, but I will research a bit, and open a new issue, if I can't crack it.

thanks

**Comment by bcoles** [comment]
> FYI I ran a quick diff check of requirements.txt (yours) and requirements.txt.bak (the original downloaded in the tar.gz),

Yeah there have been a few changes since the last release. Perhaps we should be more strict on enforcing versioning. WIth the `secure` library in particular, there had only been `0.2.x` releases for several years. A `0.3.x` release was unexpected.

**Comment by Leetcore** [comment]
I had the same problem and the requirements.txt changes solved it. Thx!

**Comment by bcoles** [comment]
This should be fixed in #1226 (once merged).

**Comment by Sd0b** [comment]
#On Ubuntu 20.10 
The tool works After  ``  pip3 install secure==0.2.1 `` And `` pip3 install networkx==2.5  ``

This resolve both : ``  cannot import name 'nx' from 'networkx' ``
`` cannot import name 'SecureHeaders' from 'secure'   ``
