### ISSUE TITLE
failed dev build on macOS 13.7.4 (22H420)

### ISSUE THREAD

**Issue by heyfinal** [smicallef/spiderfoot#1917]
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.13-universal2-cpython-313/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-10.13-universal2-cpython-313/src/lxml
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/Library/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c src/lxml/etree.c -o build/temp.macosx-10.13-universal2-cpython-313/src/lxml/etree.o -w -flat_namespace
      src/lxml/etree.c:5988:39: error: call to undeclared function '_PyInterpreterState_GetConfig'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
                                            ^
      src/lxml/etree.c:5988:107: error: member reference type 'int' is not a pointer
          __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
      src/lxml/etree.c:255376:7: error: call to undeclared function '_PyDict_SetItem_KnownHash'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        if (__Pyx_SetNameInClass(__pyx_t_2, __pyx_n_s_getitem, __pyx_t_9) < 0) __PYX_ERR(0, 97, __pyx_L1_error)
            ^
      src/lxml/etree.c:6652:38: note: expanded from macro '__Pyx_SetNameInClass'
          (likely(PyDict_CheckExact(ns)) ? _PyDict_SetItem_KnownHash(ns, name, value, ((PyASCIIObject *) name)->hash) : PyObject_SetItem(ns, name, value))
                                           ^
      src/lxml/etree.c:255376:7: note: did you mean '_PyDict_GetItem_KnownHash'?
      src/lxml/etree.c:6652:38: note: expanded from macro '__Pyx_SetNameInClass'
          (likely(PyDict_CheckExact(ns)) ? _PyDict_SetItem_KnownHash(ns, name, value, ((PyASCIIObject *) name)->hash) : PyObject_SetItem(ns, name, value))
                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/dictobject.h:38:24: note: '_PyDict_GetItem_KnownHash' declared here
      PyAPI_FUNC(PyObject *) _PyDict_GetItem_KnownHash(PyObject *mp, PyObject *key,
                             ^
      src/lxml/etree.c:264446:13: error: call to undeclared function '_PyUnicode_FastCopyCharacters'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                  _PyUnicode_FastCopyCharacters(result_uval, char_pos, uval, 0, ulength);
                  ^
      src/lxml/etree.c:264446:13: note: did you mean 'PyUnicode_CopyCharacters'?
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/unicodeobject.h:416:24: note: 'PyUnicode_CopyCharacters' declared here
      PyAPI_FUNC(Py_ssize_t) PyUnicode_CopyCharacters(
                             ^
      src/lxml/etree.c:265182:35: error: use of undeclared identifier '_PyObject_NextNotImplemented'; did you mean 'PyObject_HashNotImplemented'?
              if (unlikely(iternext == &_PyObject_NextNotImplemented))
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                        PyObject_HashNotImplemented
      src/lxml/etree.c:1096:43: note: expanded from macro 'unlikely'
        #define unlikely(x) __builtin_expect(!!(x), 0)
                                                ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/object.h:591:23: note: 'PyObject_HashNotImplemented' declared here
      PyAPI_FUNC(Py_hash_t) PyObject_HashNotImplemented(PyObject *);
                            ^
      src/lxml/etree.c:265973:13: error: call to undeclared function '_PyGen_SetStopIterationValue'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                  _PyGen_SetStopIterationValue(result);
                  ^
      src/lxml/etree.c:265973:13: note: did you mean '__Pyx_PyGen__FetchStopIterationValue'?
      src/lxml/etree.c:265728:12: note: '__Pyx_PyGen__FetchStopIterationValue' declared here
      static int __Pyx_PyGen__FetchStopIterationValue(CYTHON_UNUSED PyThreadState *__pyx_tstate, PyObject **pvalue) {
                 ^
      src/lxml/etree.c:267806:5: error: call to undeclared function '_PyErr_FormatFromCause'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          _PyErr_FormatFromCause(
          ^
      src/lxml/etree.c:268071:19: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              int ret = _PySet_NextEntry(iter_obj, ppos, value, &hash);
                        ^
      src/lxml/etree.c:269068:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      src/lxml/etree.c:269377:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      src/lxml/etree.c:269573:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      src/lxml/etree.c:269769:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      src/lxml/etree.c:270003:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      src/lxml/etree.c:270237:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      src/lxml/etree.c:270440:70: error: too few arguments to function call, expected 6, have 5
                                                    is_little, !is_unsigned);
                                                                           ^
      /Library/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      15 errors generated.
      Compile failed: command '/usr/bin/clang' failed with exit code 1
      creating tmp
      cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit44bmfzrd.c -o tmp/xmlXPathInit44bmfzrd.o
      cc tmp/xmlXPathInit44bmfzrd.o -lxml2 -o a.out
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Building wheel for ipaddr (pyproject.toml) ... done
  Created wheel for ipaddr: filename=ipaddr-2.2.0-py3-none-any.whl size=18354 sha256=47c57b50649e1267c56fdd9d3c79affa027c7c70a223ea9d4db340e37cb57d95
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/43/be/44/09bf877e98499067e9016f74cfa4411ffbf926b6f81d73626a
  Building wheel for pygexf (pyproject.toml) ... done
  Created wheel for pygexf: filename=pygexf-0.2.2-py3-none-any.whl size=5482 sha256=c6c66edcc380eff747795896997a2e284d87de030718808b933d04e2db9acd6c
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/e5/7e/ef/6f6cc25cecb4c864a6959ea0fd33378af78878bf59f023dc27
  Building wheel for python-whois (pyproject.toml) ... done
  Created wheel for python-whois: filename=python_whois-0.7.3-py3-none-any.whl size=87798 sha256=765fed48e3ac75489c8f304e9bacf0f6314770f855dc7298486d81fa50d59ad9
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/54/e0/22/c8ff8b87769c19cd022f317ed6efbe32d73d083e3d99e17058
  Building wheel for python-docx (pyproject.toml) ... done
  Created wheel for python-docx: filename=python_docx-0.8.11-py3-none-any.whl size=184569 sha256=5d1030538e76e5a7b3e4da453c99c23a8eebb2a8e451c4e14a066d493fdc0a54
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/28/d3/8e/c09119833d575c0c97e00be8df90d7a668e3df21eedcebddc0
  Building wheel for httpagentparser (pyproject.toml) ... done
  Created wheel for httpagentparser: filename=httpagentparser-1.9.5-py3-none-any.whl size=7612 sha256=7f2feffdf1d1c3472c1437af0c41e341e751911d664f74a9d367a6444edc7054
  Stored in directory: /private/var/root/Library/Caches/pip/wheels/cc/af/3a/d3a7da031d54f925797463fd56e5c0711ee09f0138e854d1cd
Successfully built ipaddr pygexf python-whois python-docx httpagentparser
Failed to build lxml
ERROR: Failed to build installable wheels for some pyproject.toml based projects (lxml)

**Comment by alejosebasp-omnipro** [comment]
I have the same problem, some solution for this issue??

**Comment by muckisg** [comment]
Same with me on MacOS 15.5 and python 3.13.5

Any hints?

Kind regards,

Maurice
